install.packages("devtools")
devtools::install_github("hadley/lazyeval")
devtools::install_github("hadley/dplyr")
devtools::install_github("rstudio/ggvis", build_vignettes = FALSE)
devtools::install_github("shiny", "rstudio")
install.packages("ggplot2")
install.packages("gcookbook")
